### PR TITLE
replacing tabs by 4 spaces - PSR-2

### PR DESCRIPTION
**Pull request by BlueManLine**
With reference to PHP PSR-2 ( https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md ) code must use 4 spaces for indenting, not tabs.

### CODE REVIEW

**Comment by 18601673727** [comment]
+1

**Comment by BlueManLine** [comment]
How about that - https://github.com/laravel/framework/commit/c0824c5d2acb46d35125062fa28a76fd0b29feac

**Comment by mikeerickson** [comment]
I am guessing we will not see this anytime soon as Jeffrey has made it pretty clear he has no desires to maintain Generators moving forward. 

Guess it is time to fork and see if this is something worthwhile maintaining into future.

**Comment by JeffreyWay** [comment]
L5 is PSR-2, not L4.

**Pull request closed without merging**
